# the different stages of this Dockerfile are meant to be built into separate images
# https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage
# https://docs.docker.com/compose/compose-file/#target


# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG PHP_VERSION=7.3
ARG NGINX_VERSION=1.17
ARG POSTGRES_VERSION=10
ARG VARNISH_VERSION=6.2
ARG APP_PROJECT=testprojet

# "php" stage
FROM php:${PHP_VERSION}-fpm-alpine AS api_platform_php

# persistent / runtime deps
RUN apk add --no-cache \
		acl \
		file \
		gettext \
		git \
		ca-certificates \
		openssh-client \
		libpng-dev \
		libjpeg-turbo-dev \
		freetype-dev \
		graphviz \
		ttf-freefont \
		imagemagick \
		libwebp-dev \
		libxml2-dev \
        rabbitmq-c-dev \
        supervisor \
	;

ARG APCU_VERSION=5.1.17
RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		icu-dev \
		libzip-dev \
		postgresql-dev \
		zlib-dev \
		g++ \
		make \
		autoconf \
		yaml-dev \
		imagemagick-dev \
	; \
	\
	docker-php-ext-configure zip --with-libzip; \
	docker-php-ext-configure gd \
        --with-jpeg-dir=/usr/include \
        --with-png-dir=/usr/include \
        --with-webp-dir=/usr/include \
        --with-freetype-dir=/usr/include; \
	docker-php-ext-install -j$(nproc) \
		intl \
		pdo_pgsql \
		zip \
		exif \
		gd \
		sysvsem \
		soap \
		bcmath\
        sockets\
	; \
	pecl install \
		apcu-${APCU_VERSION} \
		imagick \
		amqp \
	; \
	pecl clear-cache; \
	docker-php-ext-enable \
		apcu \
		opcache \
		imagick \
		amqp \
	; \
	\
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
			| tr ',' '\n' \
			| sort -u \
			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
	apk add --no-cache --virtual .api-phpexts-rundeps $runDeps; \
	\
	apk del .build-deps

COPY --from=composer:1.10.10 /usr/bin/composer /usr/bin/composer
COPY docker/php/php.ini-production $PHP_INI_DIR/php.ini-production
COPY docker/php/php.ini-development $PHP_INI_DIR/php.ini-development
RUN ln -s $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
COPY docker/php/conf.d/api-platform.ini $PHP_INI_DIR/conf.d/api-platform.ini

RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Europe/Paris  /etc/localtime
RUN echo "Europe/Paris" >  /etc/timezone

# https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
ENV COMPOSER_ALLOW_SUPERUSER=1
# install Symfony Flex globally to speed up download of Composer packages (parallelized prefetching)
RUN set -eux; \
	composer global require "symfony/flex" --prefer-dist --no-progress --no-suggest --classmap-authoritative; \
	composer clear-cache
ENV PATH="${PATH}:/root/.composer/vendor/bin"

WORKDIR /srv/api

# build for production
ARG APP_ENV=prod
ARG GITHUB_TOKEN=6984b5439b675fd723f38bc4d9040b7be491766a

# cron
COPY docker/php/crontab/root /var/spool/cron/crontabs/root
RUN chmod 600 /var/spool/cron/crontabs/root

# supervisor
COPY docker/php/supervisor.d/rabbitmq.ini /etc/supervisor.d/rabbitmq.ini
COPY docker/php/supervisord.conf /etc/supervisord.conf

COPY docker/php/php-fpm/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf

RUN set -eux \
    && mkdir ~/.ssh \
    && ssh-keyscan github.com >> ~/.ssh/known_hosts \
    && composer config -g github-oauth.github.com "${GITHUB_TOKEN}"

# prevent the reinstallation of vendors at every changes in the source code
COPY composer.json composer.lock symfony.lock ./
# do not use .env files in production
RUN echo '<?php return [];' > .env.local.php
RUN set -eux; \
	composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress --no-suggest; \
	composer clear-cache

# copy only specifically what we need
COPY bin bin/
COPY config config/
COPY public public/
COPY private private/
COPY src src/
COPY templates templates/
COPY translations translations/

COPY package.json package-lock.json ./
RUN apk add --update nghttp2-dev nodejs npm
RUN npm i

RUN set -eux; \
	mkdir -p var/cache var/log; \
	composer dump-autoload --classmap-authoritative --no-dev; \
	chmod +x bin/console; sync
VOLUME /srv/api/var

COPY docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]
CMD ["php-fpm"]


# "nginx" stage
# depends on the "php" stage above
FROM nginx:${NGINX_VERSION}-alpine AS api_platform_nginx

ARG APP_PROJECT

RUN apk add openssl
RUN mkdir -p /etc/nginx/ssl/api; \
	openssl genrsa -out /etc/nginx/ssl/api/server.key 2048; \
	openssl req -new -key /etc/nginx/ssl/api/server.key -out /etc/nginx/ssl/api/server.csr -subj "/C=FR/ST=France/L=Lille/O=Disruptual/OU=IT/CN=*.sandbox.api.disruptual.com/emailAddress=tech@disruptual.com"; \
	openssl x509 -req -days 365 -in /etc/nginx/ssl/api/server.csr -signkey /etc/nginx/ssl/api/server.key -out /etc/nginx/ssl/api/server.crt

RUN mkdir -p /etc/nginx/ssl/front; \
	openssl genrsa -out /etc/nginx/ssl/front/server.key 2048; \
	openssl req -new -key /etc/nginx/ssl/front/server.key -out /etc/nginx/ssl/front/server.csr -subj "/C=FR/ST=France/L=Lille/O=Disruptual/OU=IT/CN=*.sandbox.disruptual.com/emailAddress=tech@disruptual.com"; \
	openssl x509 -req -days 365 -in /etc/nginx/ssl/front/server.csr -signkey /etc/nginx/ssl/front/server.key -out /etc/nginx/ssl/front/server.crt

COPY docker/nginx/conf.d/${APP_PROJECT}/default.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/conf.d/includes/proxy.conf /etc/nginx/conf.d/includes/proxy.conf

WORKDIR /srv/api

COPY --from=api_platform_php /srv/api/public public/
COPY --from=api_platform_php /srv/api/private private/


# "db" stage
FROM postgres:${POSTGRES_VERSION}-alpine AS api_platform_db
COPY docker/postgres/wrapper.sh /
RUN chmod +x /wrapper.sh
ENTRYPOINT ["/wrapper.sh"]
CMD ["postgres", "-c", "logging_collector=on", "-c", "log_connections=on", "-c", "log_directory=/logs", "-c", "log_filename=postgresql.log"]
RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Europe/Paris  /etc/localtime
RUN echo "Europe/Paris" >  /etc/timezone


# "varnish" stage
# does not depend on any of the above stages, but placed here to keep everything in one Dockerfile
FROM cooptilleuls/varnish:${VARNISH_VERSION}-alpine AS api_platform_varnish

COPY docker/varnish/conf/default.vcl /usr/local/etc/varnish/default.vcl
CMD ["varnishd", "-F", "-f", "/usr/local/etc/varnish/default.vcl", "-p", "http_resp_hdr_len=1024k", "-p", "http_resp_size=1024k", "-p", "http_req_hdr_len=64k", "-p", "workspace_backend=256k", "-p", "workspace_client=256k", "-p", "http_max_hdr=256", "-p", "thread_pool_min=1000", "-p", "thread_pool_max=10000", "-p", "thread_pools=8"]


# "php-dev" stage
# enable xdebug, for local use only
FROM api_platform_php AS api_platform_php_dev

ARG XDEBUG_VERSION=2.7.1
ENV ENV="/etc/profile"

COPY docker/php/xdebug.ini $PHP_INI_DIR/conf.d/xdebug.ini
RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
		autoconf \
		g++ \
		make \
    ; \
    pecl install xdebug-${XDEBUG_VERSION}; \
    docker-php-ext-enable xdebug; \
    touch /tmp/php7-xdebug.log; \
    chmod 777 /tmp/php7-xdebug.log; \
    apk del .build-deps
